version: '3'

services:
  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./fullchain.pem:/etc/nginx/cert/fullchain.pem
    - ./privkey.pem:/etc/nginx/cert/privkey.pem
    ports:
    - "80:80"
    - "443:443"

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: https://progression.ranger.quest/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus.yml"
      - --web.external-url=https://progression.ranger.quest/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
      - prometheus-data:/prometheus
    restart: always

volumes:
  prometheus-data: